### ISSUE TITLE
Sweep parameter is not working

### ISSUE THREAD

**Issue by aburousan** [Qucs/qucs#1066]
I am using qucs 0.019. Here whenever i am trying to sweep the value of RO, i am having an error saying ```Undefined number [RO]```
I have included a screenshot below.
![Screenshot from 2022-09-20 19-51-29](https://user-images.githubusercontent.com/60939745/191284554-34505fb6-c9c8-45b8-99bc-7ed6a513dfbf.png)

**Comment by ra3xdh** [comment]
I see Qucs-S on this screenshot. At first please switch to the latest release 0.0.24. The 0.0.19 is outdated. See https://github.com/ra3xdh/qucs_s/releases/tag/0.0.24 for more info. You need to define the value for resistance to make DC sweep operational. Ngspice cannot sweep variables. Component reference is required instead. You should enter somethink like `R=1k` for `RO` resistance. But `R=RO` is not valid and produce undefined variable error. 

Please ask questions about Qucs-S at the dedicated github page: https://github.com/ra3xdh/qucs_s/issues but not here. This is Qucs project page.  I am closing this issue because it is related to Qucs-S but not to Qucs.
