### ISSUE TITLE
Change in Qucs Home requires restart.

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#446]
When the user changes the "File > Application Settings > Locations > Qucs Home" a restart is required.
Can't we just close all the open projects/tabs and reload the list of projects from the new location?

**Comment by guitorri** [comment]
Related: Pressing the '...' button to find the new Qucs Home launches a dialog that does not look native on Windows.

![image](https://cloud.githubusercontent.com/assets/1388949/12855759/8168301e-cc41-11e5-8cf1-97920f9f27b6.png)

**Comment by in3otd** [comment]
@crobarcro I was looking at the Application Settings dialog and noticed that the "Add Path with SubFolders" button actually adds *just* the subfolders not also the selected directory itself. Is this intended?
Seems a bit confusing to me, since the button just above, "Add Path", adds the selected directory (as expected)

**Comment by crobarcro** [comment]
Yes, this is a bug, it should also add the directory
