### ISSUE TITLE
Contents tab, project name takes a lot of space.

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#447]
See below. On OSX it is not like that. Only the project name is shown, no path.

![image](https://cloud.githubusercontent.com/assets/1388949/12855814/dcddb5cc-cc41-11e5-8149-d6d28925d339.png)

**Comment by in3otd** [comment]
I guess this could be because [here] (https://github.com/Qucs/qucs/blob/master/qucs/qucs/projectView.cpp#L62-L65) `QDir::separator()` is used, which gives the OS-dependent native separator, while AFAIU the paths in a `QDir` internally always use `/` as separator.
Cannot yet build on Windows so could not try this.
