### ISSUE TITLE
appveyor and check

### ISSUE THREAD

**Issue by felix-salfelder** [Qucs/qucs#468]
appveyor does not run `make distcheck`. not even `check`. i think this is bad.
(apologies if there's already an issue, couldn't find it)

**Comment by guitorri** [comment]
It might be possible. The problem is to setup Tex for `qucs-doc` and Python for `qucs-test` on AppVeyor.
Some bits about Tex:
 - https://github.com/thomasjo/atom-latex/blob/master/.appveyor.yml
 - https://github.com/thomasjo/atom-latex/blob/master/script/install-miktex

Added this to the checklist in #431 (we might shirt some tasks to future releases).
