### ISSUE TITLE
Spice4qucs: issue with some Xyce .OPTION package names...

### ISSUE THREAD

**Issue by jfred31** [Qucs/qucs#516]
Some Xyce .OPTION package names contains a "-" character that does not show up in the component dialog, and at the end in the netlist. As a result, simulation crashes immediately:
> ***** Reading and parsing netlist...
> Netlist error in file
>  C:\xxxx\spice4qucs.hb.cir at or near
>  line 2
>  Unrecognized .OPTIONS package NONLINHB

NONLIN**-**HB is the correct package name there...

A quick look into the code shows that the property is correctly defined (sp_option.cpp, SpiceOptions::SpiceOptions() method), but it seems that component dialog removes the "-" character for some reason (componentdialog.cpp, ComponentDialog::slotSelectProperty() method ?).
Is there a good reason to remove "-" from all combobox properties? Can that be fixed?

Thanks,

JF

**Comment by ra3xdh** [comment]
Digging into code I have found that `"-"` removing was introduced around 2004. I think it was valid symbols set for property value in Qucsator engine. 

I decided to preserve this code. But I modified `SpiceOption` component to allow manual editing of `pkg` field instead of predefined set of option groups in ComboBox. XYCE development is very fast and always may be introduced new options. And spice4qucs subsystem can lag. Manual editing provides a more flexible way for such cases. See commit b862d56 for possible fix.
