### ISSUE TITLE
"Move Up/Down" buttons greyed out in the equation property window

### ISSUE THREAD

**Issue by pidgeon777** [Qucs/qucs#541]
I created a list of equations:

![image](https://cloud.githubusercontent.com/assets/13739892/16751280/664685b6-47d8-11e6-8787-8d5eea335c2e.png)

It is impossible to modify the order of the displayed equations, because the "Move Up/Down" buttons are greyed out in the equation property window:

![image](https://cloud.githubusercontent.com/assets/13739892/16751249/2aed8e92-47d8-11e6-906e-08c4234b59e2.png)

I'm using Qucs v0.0.19 (qucs-win64-bin portable version), running it on a Windows 7 x64 machine.

**Comment by in3otd** [comment]
Thanks for finding this bug! If you switch the application language to English then it will work as expected ...

The problem comes from [here](https://github.com/Qucs/qucs/blob/master/qucs/qucs/components/componentdialog.cpp#L588), the comparison should be with `tr("equation")` (But I think a translator could mess up this anyway, proposing a different translation here and in the Equation component description, or am I wrong?).

**Comment by pidgeon777** [comment]
Probably it's as you're suggesting, maybe the translator has some effect even on the description of the equation... after the translation, the test in the code won't work anymore ("equation" get translated to "equazione" when using Italian language).

**Comment by guitorri** [comment]
Fixed with #548.
